---
title: "Salmon aquaculture in Chile: Production growth and socio-economic impact"
date: 2024-03-05
author:
  - name: Adams Ceballos-Concha
    affiliation: Food and Resources Economics Department, University of Florida
  - name: Frank Asche
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
  - name: Roberto Cárdenas-Retamal
    orcid: 0000-0002-9578-827X
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
categories:
  - Salmon Industry
  - Socio-Economic impact
  - Aquaculture
  - Chile
pub-info:
  reference: >-
    <a>Adams Ceballos-Concha</a>, <a>Frank Asche</a>, and <strong>Roberto Cárdenas-Retamal</strong>, “Salmon aquaculture in Chile: Production growth and socio-economic impact”
#  links:
 # - name: Code
  #  url: https://github.com/vincentarelbundock/mfxplainer
  #  icon: fa-brands fa-github
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
---


## Abstract

Global aquaculture has presented significant growth rates over the last decades and has contributed to the food security agenda and SDG’s objectives. However, has been considered a controversial activity raising concerns about environmental impacts, sociocultural and economic issues, and health. Chilean salmon aquaculture has shown impressive development in production growth, but controversies are not exempt in this industry. Despite having created employment at the local level, it is not particularly welcome in the localities where it operates. There is a widespread opinion that local communities have remained relatively excluded from the economic benefits associated with the industry. This may condition the development of an important industrial activity such as salmon aquaculture. In this paper, we discuss the socio-economic impacts that the salmon industry delivered in southern Chile. The focus is primarily on variables such as employment, salaries, poverty, unionism, income distribution, and migration. Although the socioeconomic effects that the industry initially triggered are widely criticized in the literature, the performance of recent decades indicates that these conditions have improved steadily over time, specifically significantly contributing to the country's economic growth and development, particularly in rural areas. The industry has created well-paying jobs, mitigated poverty rates, reduced income inequality, and provided an alternative for people with limited employment opportunities.