---
title: "Impact assessment of salmon farming on income distribution in remote coastal areas: The Chilean case"
date: 2021-03-29
author:
  - name: Roberto Cárdenas-Retamal
    affiliation: University of Florida
    orcid: 0000-0002-9578-827X
  - name: Jorge Dresdner-Cid
    affiliation: Universidad de Concepcion
  - name: Adams Ceballos-Concha
    affiliation: Univeristy of Florida
categories: 
  - Income distribution
  - Salmon aquaculture
  - Remote coastal areas
  - Impact evaluation
  - Chile
pub-info:
  links:
    - name: Final version
      url: https://doi.org/10.1016/j.foodpol.2021.102078
      icon: fa-solid fa-scroll
    # - name: Code
    #   url: https://github.com/andrewheiss/ngo-crackdowns-philanthropy
    #   icon: fa-brands fa-github
    # - name: Data
    #   url: https://github.com/andrewheiss/ngo-crackdowns-philanthropy/tree/master/data
    #   icon: fa-solid fa-table
    # - name: Add to Zotero
    #   url: https://www.zotero.org/save?type=doi&q=10.1016/j.foodpol.2021.102078
    #   icon: ai ai-zotero
  reference: >-
    <a><strong>Cárdenas-Retamal, R.</strong></a>, <a>Dresdner-Cid, J.</a>, and <a>Ceballos-Concha, A.</a>, (2021) “Impact assessment of salmon farming on income distribution in remote coastal areas: The Chilean case,” <em>Food Policy</em> 101: 102078, doi: <a href="https://doi.org/10.1016/j.foodpol.2021.102078"><code>10.1016/j.foodpol.2021.102078</code></a>
  extra: >-
    Presented at the V International Conference COES: ”Concentrations” in 2018, and in the X Annual Meeting of the Chilean Society of Regional Studies SOCHER in 2018.
doi: 10.1016/j.foodpol.2021.102078
haiku: 
 #   - Income inequality in areas with salmon farms fell significantly compared to areas without farms.
#    - The installment of salmon farms in remote coastal areas dampened the general trend of increased income inequality.
 #   - The impact is equivalent to a reduction in the Gini coefficient from 0.479 to 0.464.
---

## Abstract

We analyzed the impact that the advent of the salmon aquaculture industry had on income distribution in coastal communities. Specifically, we evaluated whether salmon farms generated significant changes on household income distribution in the remote coastal areas of the Los Lagos region in Chile between 1992 and 2002. Salmon farms were expected to generate new labor and income opportunities for the local population. The impact on income distribution in the area should depend on which type of households were favored with this increased labor demand: low-income or high-income households. We tested this by applying impact evaluation techniques. Changes in income distribution were measured using Gini, Theil, and Mean Log Deviation (MLD) indices. We used information generated by small area estimation methods to measure individual household incomes. This latter was utilized to calculate the distribution indices at the locality level. We controlled for pre-existing differences and observable characteristics in the treatment group. Our results show that income inequality in areas with salmon farms fell significantly compared to areas without farms and this attenuated a general trend towards increasing inequality in the rural sector. These results are conditioned by the zone of influence of salmon farming, since the distance between the farm and the locality plays an important role in the impact on inequality. Finally, our results suggest that improvements in the position of households with medium incomes explain the reduction in income inequality.


<!-- ## Citation -->

<!-- <p class="buttons" style="text-align:center;"> -->
<!-- <a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1177/0899764020971045">{{< ai zotero >}}&emsp;Add to Zotero {{< fa square-arrow-up-right >}}</a> -->
<!-- </p> -->

<!-- ```bibtex -->
<!-- @article{CARDENASRETAMAL2021102078, -->
<!-- title = {Impact assessment of salmon farming on income distribution in remote coastal areas: The Chilean case}, -->
<!-- journal = {Food Policy}, -->
<!-- volume = {101}, -->
<!-- pages = {102078}, -->
<!-- year = {2021}, -->
<!-- issn = {0306-9192}, -->
<!-- doi = {https://doi.org/10.1016/j.foodpol.2021.102078}, -->
<!-- url = {https://www.sciencedirect.com/science/article/pii/S0306919221000555}, -->
<!-- author = {Roberto Cárdenas-Retamal and Jorge Dresdner-Cid and Adams Ceballos-Concha}, -->
<!-- keywords = {Income distribution, Salmon aquaculture, Remote coastal areas, Impact evaluation, Chile} -->
<!-- } -->
<!-- ``` -->
