---
title: "Risk perception and production risk in seaweed aquaculture"
date: 2024-03-06
author:
  - name: César Salazar
    affiliation: Universidad del Bio-Bio
  - name: Marcela Jaime
    affiliation: Universidad de Concepción
  - name: Roberto Cárdenas-Retamal
    orcid: 0000-0002-9578-827X
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
  - name: Francisco Hernandez
    affiliation: Universidad del Bio-Bío
categories:
  - Production risk
  - Sample selection
  - Seaweed aquaculture
pub-info:
   links:
    - name: Final version
      url: https://doi.org/10.1080/13657305.2024.2342270
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1016/j.foodpol.2021.102078
      icon: ai ai-zotero
  reference: >- 
   <a>César Salazar</a>, <a>Marcela Jaime</a>, <a><strong>Cárdenas-Retamal, R.</strong></a>, and <a>Francisco Hernandez</a>. (2024) “Risk perception and production risk in seaweed aquaculture”. <em>Aquaculture Economics & Management</em> 1-29, doi: <a href="https://doi.org/10.1080/13657305.2024.2342270"><code>10.1080/13657305.2024.2342270</code></a>

  
#  links:
 # - name: Code
  #  url: https://github.com/vincentarelbundock/mfxplainer
  #  icon: fa-brands fa-github
doi: 10.1080/13657305.2024.2342270 
# haiku:
#  - Forthcoming in Aquaculture Economics and Managment
---


## Abstract

Risk is an inherent characteristic of aquaculture production. For a holistic understanding of risk, the risk assessment process must account for both subjective and objective dimensions of risk. This paper empirically studies the role of risk perception and the risk properties of inputs used in aquaculture to explain the low adoption rates of seaweed farming in Chile. We propose a risk production estimation framework with selectivity to explore the role of risk, given that many aquaculture concessions remain totally or partially unexploited. We found that farmers are more likely to produce seaweed when they perceive greater access to financing, but also that this activity is more exposed to theft than other activities. Moreover, results suggest that labor and energy are risk-increasing inputs, while we found that capital and the number of hectares available are risk-decreasing inputs. The latter is important as it suggests that larger seaweed producers and more investment would reduce production variability.