---
title: "More than just a break: Performance after walking in green and urban spaces"
date: 2026-03-29
author:
  - name: Jianhui Liu
    affiliation: University of Florida
  - name: Tongzhe Li
    affiliation: University of Guelph
  - name: Mark Patton
    affiliation: Statistics Canada
  - name: Roberto Cárdenas-Retamal
    orcid: 0000-0002-9578-827X
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
  - name: Danielle Roy
    affiliation: University of Guelph
categories:
  - Green space
  - Urban space
  - Productivity
  - Framed field experiment
pub-info:
  links:
    - name: Final version
      url: https://doi.org/10.1080/00036846.2026.2652062
      icon: fa-solid fa-scroll
    - name: Free access
      url: https://www.tandfonline.com/eprint/QUPWNSKXJYNES8CGBNN6/full?target=10.1080/00036846.2026.2652062
      icon: fa-solid fa-unlock
  reference: >-
    <a>Liu, J.</a>, <a>Li, T.</a>, <a>Patton, M.</a>, <a><strong>Cárdenas-Retamal, R.</strong></a> and <a>Roy, D.</a> (2026). "More than just a break: Performance after walking in green and urban spaces". <em>Applied Economics</em> 1-16, doi: <a href="https://doi.org/10.1080/00036846.2026.2652062"><code>10.1080/00036846.2026.2652062</code></a>
doi: 10.1080/00036846.2026.2652062
---

## Abstract

Increasing productivity at the individual level is influenced by a complex mix of factors.
While the literature generally suggests that green space exposure may enhance
attention and well-being, urban environments are often perceived as less beneficial
due to factors like noise and artificial design. This study investigates the effects of
acute green and urban space exposure on productivity, aiming to fill a critical research
gap in understanding how short-term environmental exposure impacts real-world
performance. Using a lab-in-the-field experiment, we measured productivity through a
math test and mental well-being via the Rosenberg Self-Esteem Scale. A total of 222
participants completed both tests before and after a 20-minute treatment, involving a
randomized walk in either a green or urban space, while a control group remained
indoors. Significant treatment effects were observed within specific subgroups:
infrequent green space visitors showed enhanced productivity after an urban walk,
while frequent green space visitors experienced decreased productivity following a
green space walk. Gender differences also emerged, with female participants reporting
a boost in self-esteem after a walk in a green space, whereas both green and urban
spaces led to declines in self-esteem for male participants. By addressing this research
gap, our study challenges assumptions about the universal benefits of green space
exposure and emphasizes the importance of tailoring environmental interventions.
These insights offer valuable guidance for employers and urban planners in designing
environments that enhance productivity and well-being across diverse populations.
