---
title: "Diet-related Disease and Consumer Behavior: Seafood Purchasing Responses to Type 2 Diabetes Diagnosis"
date: 2024-03-05
author:
  - name: Roberto Cárdenas-Retamal
    orcid: 0000-0002-9578-827X
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
  - name: Di Fang
    affiliation: Food and Resources Economics Department, University of Florida
  - name: Frank Asche
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
categories:
  - Seafood 
  - WIC program
  - Healthy diets
  - Disease diagnosis
  - Food policy 
  - Scanner data
pub-info:
  reference: >-
    “Seafood Purchasing in Responses to Type 2 Diabetes Diagnosis”

pub-status: 
  status: Writing
  class: warning
  icon: "fa-solid fa-pencil"
  
haiku: 
  - Presented at the Agricultural & Applied Ecoonmics Association (AAEA) 2024 conference in New Orleans
  
---

# Abstract 

Disease diagnosis can be a critical turning point in individuals’ lives and incentivize them to make lifestyle changes.
However, the extent to which these events lead to significant changes in short- and long-term food choices and the
extent to which this depends on demographics remain less studied. Seafood is a food group that is particularly interesting
in this context. Despite well-documented health benefits, seafood consumption remains below recommended
levels and vary significantly between demographic groups. Using a specific food group also allows the use of quantities
in addition to expenditure or an index which may be important due to the closer relationship with nutrients,
as well as exploring adjustments of the composition of products. Using the NielsenIQ datasets, this study examines
how a type 2 diabetes diagnosis affected seafood purchasing behaviors in the United States, using a two-stage difference
in difference approach. Our findings show a significant increase in seafood purchases post-diagnosis by 2%;
the persistence of the impact vary about 8 years, before the effect eventually declines. There is heterogeneity in the
results, showing that demographic differences in households play an important role in seafood purchases responses
to a diagnosis, as well seafood species. Of particular interest is the fact that canned seafood was included in the Special
Supplemental Nutrition Program for Women, Infants, and Children in the U.S. in 2024, increasing access to low
income households that traditionally are among the groups that consumes least seafood. Our results indicate strong
positive responses for canned seafood for low income households.
