---
title: "Risk perception and production risk in seaweed aquaculture"
date: 2024-03-06
author:
  - name: César Salazar
    affiliation: Universidad del Bio-Bio
  - name: Marcela Jaime
    affiliation: Universidad de Concepción
  - name: Roberto Cárdenas-Retamal
    orcid: 0000-0002-9578-827X
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
  - name: Francisco Hernandez
    affiliation: Unievrsidad del Bio-Bío
categories:
  - Production risk
  - Sample selection
  - Seaweed aquaculture
pub-info:
  reference: >-
    <a>César Salazar</a>, <a>Marcela Jaime</a>, <strong>Roberto Cárdenas-Retamal</strong> and <a>Francisco Hernandez</a>. “Risk perception and production risk in seaweed aquaculture”.
#  links:
 # - name: Code
  #  url: https://github.com/vincentarelbundock/mfxplainer
  #  icon: fa-brands fa-github
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
  
haiku:
  - Review and resubmit in Aquaculture Economics and Managment
---


## Abstract

Risk is an inherent characteristic of aquaculture production. For a holistic understanding of risk, the risk assessment process must account for both subjective and objective dimensions of risk. This paper empirically studies the role of risk perception and the risk properties of inputs used in aquaculture to explain the low adoption rates of seaweed farming in Chile. We propose a risk production estimation framework with selectivity to explore the role of both kinds of risk given that many of aquaculture concessions remain totally or partially unexploited. We found that farmers are more likely to produce seaweed as they perceive that there is greater access to financing, and as this activity is more exposed to robbery than other activities. The latter is in line with aquaculture producers being more risk tolerant. Moreover, results suggest that labor and energy are risk-increasing inputs, meaning that production variability increases as the use of these variables increases. These results may signal an excess of labor or labor’s inability to monitor environmental conditions, especially as marine area increases. In addition, we found that capital and hectares are risk-decreasing inputs, suggesting that larger fish farms and more investment in farming tools would reduce production variability.