---
title: "Labor outcomes effect of mental health"
date: 2025-12-01
author:
  - name: Roberto Cárdenas-Retamal
    orcid: 0000-0002-9578-827X
    affiliation: School of Forest, Fisheries, & Geomatics Sciences, University of Florida
 
categories:
  - Mental health
  - Depression
  - Anxiety
  - Labor outcomes
pub-info:
  reference: >-
    “Labor outcomes effect of mental health”
#  links:
 # - name: Code
  #  url: https://github.com/vincentarelbundock/mfxplainer
  #  icon: fa-brands fa-github
pub-status: 
  status: Writing
  class: warning
  icon: "fa-solid fa-pencil"
  

---

# Abstract 

A chronic disease diagnosis is an event that can be a turning point in an individual’s lifestyle, affecting several behavioral dimensions, such as diet patterns (Edenbrandt et al., 2025; Hut & Oster, 2022), crime behavior (Andersen et al., 2025), prevalence of healthy behaviors, a change in alcohol use (Pinto & Trunzo, 2005), and labor market outcomes (Ramirez Lizardi et al., 2024). Mental health is a diagnosis that is particularly interesting from a behavioral perspective because it has multiple possible implications for the diagnosed individuals in terms of their economic, professional, and social life, as well as for health policy (Chisholm et al., 2016; Horwitz, 2011; Stecher et al., 2024). 
Globally, the most common mental disorders are anxiety and depression, and most people do not have access to effective care, even though effective prevention and treatment options exist. In 2016, it was estimated that 12 billion productive days were lost every year to depression and anxiety across 36 countries in the world, at a cost of nearly US$1 trillion, which included days lost to absenteeism, presenteeism, and staff turnover. Some of the social costs of depression are reduced educational attainment, lower wages, and costs to employers, as well as in labor force participation and productivity (Lerner & Henke, 2008). Individuals with a depression diagnosis can become an increasing cause of disability, suicides, and disease burden, and tend to coexist with other noncommunicable diseases (Hsieh & Qin, 2018).
The relationship between mental health illness and labor outcomes is well documented in the literature; however, the causal effect of depression and anxiety on labor outcomes is less studied, despite the social consequences associated with those diseases. This relationship also faces some challenges because of the endogeneity problem of mental health diseases. 
The objective of this paper is to estimate how labor outcomes, specifically wages and employment, respond to a depression or anxiety diagnosis in households.  We use a representative longitudinal panel data set from NielsenIQ Consumer Panel Data, complemented with the Annual Ailments, Health, and Wellness Survey. The Ailment data provides health information for a subset of panelists' households from the consumer panel data. This allows us to track when households were diagnosed with depression or anxiety, while using the consumer panel allows us to extract demographic information from households. We employed a difference-in-differences design to estimate the effect of the diagnosis on labor outcomes. 
We find a statistically significant decrease in wages on average of 20% following a mental health diagnosis. This effect is small in the first years after the diagnosis, intensifying over time and being persistent for seven years. In addition to this, we show that the results are consistent across demographic heterogeneity, such as marital status (being stronger in divorced and single households), race, head of household age, household composition (stronger when living alone), and family type. We also find that the probability of being unemployed after the mental health diagnosis increases by 10%, but the effect is significant only after the fifth year of the diagnosis. 
This article makes several contributions. First, we expand the scarce evidence on the causal effects of health shocks on labor outcomes, providing evidence on how households present large and persistent declines in wages and increases in unemployment after a mental health diagnosis. The magnitude and long-run effects suggest that mental health conditions create substantial economic costs for households. Secondly, the heterogeneous impacts across demographic household attributes highlight that some population groups, particularly divorced, single, and single-person households, are more vulnerable to labor market disruptions following a mental health shock. Those results underscore the potential economic returns to early mental health detection, timely treatment, and workplace accommodations. Addressing mental health conditions nay not only improve individual well-being, but also mitigate long-term productivity in the labor market. 

