---
title: "Women engagement, psychological traits, and gender gapsin the small-scale seaweed aquaculture in Chile"
date: 2023-01-15
author:
  - name: César Salazar
    affiliation: Universidad del Bio-Bio. Research Nucleus on Environmental and Natural Resource Economics (NENRE)-EfD Chile
    orcid: 0000-0002-0199-7688
  - name: Marcela Jaime
    affiliation: Universidad de Concepcion. Research Nucleus on Environmental and Natural Resource Economics (NENRE) EfD-Chile, Centre of Applied Ecology and Sustainability (CAPES)
  - name: Roberto Cárdenas-Retamal
    affiliation: Departamento de Economía. Facultad deCiencias Económicas y Administrativas, Universidad Católica de la Santísima Concepción. Interdisciplinary Center forAquaculture Research (INCAR)
    orcid: 0000-0002-9578-827X
  - name: Marjorie Baquedano
    affiliation: Departamento de Educación Médica, Universidad de Concepción and Interdisciplinary Center for Aquaculture Research (INCAR)
categories: 
  - Gender gaps
  - Production process
  - Psychological traits
  - Small-scale aquaculture
  - Women engagement
pub-info:
  links:
    - name: Final version
      url: https://doi.org/10.1111/raq.12793
      icon: fa-solid fa-scroll
    # - name: Code
    #   url: https://github.com/andrewheiss/ngo-crackdowns-philanthropy
    #   icon: fa-brands fa-github
    # - name: Data
    #   url: https://github.com/andrewheiss/ngo-crackdowns-philanthropy/tree/master/data
    #   icon: fa-solid fa-table
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1016/j.foodpol.2021.102078
      icon: ai ai-zotero
  reference: >-
    <a>Salazar, C.</a>, <a>Jaime, M</a>, <a><strong>Cárdenas-Retamal, R.</strong> </a> and <a>Baquedano, M.</a> (2023). “Women engagement, psychological traits, and gender gaps in the small-scale seaweed aquaculture in Chile”. <em>Reviews in Aquaculture</em> 15(4):1540-1553, doi: <a href="https://doi.org/10.1111/raq.12793"><code>10.1111/raq.12793</code></a>
#  extra: >-
#    Presented at the V International Conference COES: ”Concentrations” in 2018, and in the X Annual Meeting of the Chilean Society of Regional Studies SOCHER in 2018.
doi: 10.1111/raq.12793
haiku: 
 #   - Income inequality in areas with salmon farms fell significantly compared to areas without farms.
#    - The installment of salmon farms in remote coastal areas dampened the general trend of increased income inequality.
 #   - The impact is equivalent to a reduction in the Gini coefficient from 0.479 to 0.464.
---

## Abstract

Women's participation in small-scale aquaculture is growing, but women producers remain in a disadvantaged position compared to men. Reducing gender gaps is at the core of many development programs, but little is known regarding the source of these differences. This paper investigates the main drivers of gender gaps in seaweed small-scale aquaculture by focusing on the analysis of differences between male and women, and across a series of psychological traits. We use data from a sample of 152 seaweed producers from central-southern Chile and perform a matching procedure to generate a balanced sample of male and female producers in the dimensions determining their performance in the sector. Our results show that female producers may exhibit more positive psychological traits such as patience and interpersonal trust. However, women's choices in seaweed farming may be incongruent with these characteristics, as expecting more immediate returns than males, and may not be able to exploit the advantages of collaboration in selling in the sector. This supports the notion that opportunity costs (e.g., other activities in the marine area) and outside options (e.g., fishing versus trade) may be one of the major drivers of gender gaps and suggests that there are barriers keeping women from exploiting their potentially advantageous individual characteristics. Results provide important insights for the design of support instruments aimed at reducing these barriers faced by women in the sector


<!-- ## Citation -->

<!-- <p class="buttons" style="text-align:center;"> -->
<!-- <a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1177/0899764020971045">{{< ai zotero >}}&emsp;Add to Zotero {{< fa square-arrow-up-right >}}</a> -->
<!-- </p> -->

<!-- ```bibtex -->
<!-- @article{Salazar2023, -->
<!--   title = {Women engagement,  psychological traits,  and gender gaps in the small‐scale seaweed aquaculture in Chile}, -->
<!--   volume = {15}, -->
<!--   ISSN = {1753-5131}, -->
<!--   url = {http://dx.doi.org/10.1111/raq.12793}, -->
<!--   DOI = {10.1111/raq.12793}, -->
<!--   number = {4}, -->
<!--   journal = {Reviews in Aquaculture}, -->
<!--   publisher = {Wiley}, -->
<!--   author = {Salazar,  César and Jaime,  Marcela and Retamal,  Roberto Cárdenas and Baquedano,  Marjorie}, -->
<!--   year = {2023}, -->
<!--   month = jan, -->
<!--   pages = {1540–1553} -->
<!-- } -->
<!-- ``` -->
